/* 🤖 this file was generated by svg-to-ts*/
export * from './build/myIcon-expressionLess.icon';
export * from './build/myIcon-full.icon';
export * from './build/myIcon-laughing.icon';
export * from './build/myIcon-smiling-face.icon';
export * from './build/completeIconSet';
export * from './build/my-icon.model';
